apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-installation
  namespace: argocd
spec:
  destination:
    name: ''  # Use the default cluster
    namespace: kube-system  # Sealed Secrets is often installed in the kube-system namespace
  project: default  # ArgoCD project
  source:
    repoURL: 'https://github.com/bitnami-labs/sealed-secrets'  # GitHub repository for Sealed Secrets
    targetRevision: master  # Branch name (e.g., master or main)
    path: releases/latest/controller.yaml  # Path to the Sealed Secrets controller manifest
  syncPolicy:
    automated:
      prune: true  # Automatically prune resources that are no longer defined in the repo
      selfHeal: true  # Automatically fix drift between Git and Kubernetes
